name: waveform_recorder
description: "A Flutter package for recording audio with real-time waveform visualization, ideal for voice messaging and audio recording features in chat applications."
version: 1.6.3
homepage: https://github.com/csells/waveform_recorder

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  gap: ^3.0.1
  http: ^1.2.2
  path: ^1.6.3
  path_provider: ^2.1.4
  record: ^5.1.2
  waveform_flutter: ^1.2.0
  web: ^1.1.0


